- name: Abre portas tcp nos workers
  ufw:
    rule: allow
    port: '7946'
    interface: eth1
    proto: tcp
    direction: in

- name: Abre portas udp nos workers
  ufw:
    rule: allow
    port: "{{ item }}"
    interface: eth1
    proto: udp
    direction: in
  with_items:
    - 7946
    - 4789

# - name: Dump remote addr
#   debug:
#     msg: "{{ hostvars[groups['managers'][0]]['ansible_eth1']['ipv4']['address'] }}:2377"

- name: Adiciona os outros swarms Workers
  docker_swarm:
    state: join
    advertise_addr: 'eth1'
    join_token: "{{ swarm_info.swarm_facts.JoinTokens.Worker }}"
    remote_addrs: "{{ hostvars[groups['managers'][0]]['ansible_eth1']['ipv4']['address'] }}:2377"
  when: "inventory_hostname != groups['managers'][0]"
