- name: Abre portas tcp nos managers
  ufw:
    rule: allow
    port: "{{ item }}"
    interface: eth1
    proto: tcp
    direction: in
  with_items:
    - 2377
    - 7946
    
- name: Abre portas udp nos managers
  ufw:
    rule: allow
    port: "{{ item }}"
    interface: eth1
    proto: udp
    direction: in
  with_items:
    - 7946
    - 4789

- name: Cria o cluster no primeiro servidor
  docker_swarm:
    state: present
    advertise_addr: "eth1:2377"
    #advertise_addr: "{{ hostvars[groups['managers'][0]]['ansible_eth1']['ipv4']['address'] }}"
  when: "inventory_hostname == groups['managers'][0]"

# - name: Dump advertise_addr
#   debug:
#     msg: "{{ hostvars[groups['managers'][0]]['ansible_eth1']['ipv4']['address'] }}"
