
- name: Generate client key
  openssl_privatekey:
    path: ./certs/key.pem

- name: Create the client CSR
  openssl_csr:
    path: ./certs/client.csr
    privatekey_path: ./certs/key.pem
    common_name: client
    extended_key_usage:
      - clientAuth

- name: Create the client certificate
  openssl_certificate:
    path: ./certs/cert.pem
    csr_path: ./certs/client.csr
    ownca_path: ./certs/ca.pem
    ownca_privatekey_path: ./certs/ca-key.pem
    provider: ownca
